# Site settings
title: Styleguide Bootstrap
email: luismetzger@me.com
description: > # this means to ignore newlines until "baseurl:"
  Styleguide Code Sample for Simple
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://luismetzger.com" # the base hostname & protocol for your site
twitter_username: luisgmetzger
github_username:  luismetzger

# Build settings
markdown: kramdown


#Permalink SEO friendly
permalink: pretty

#Let's Compress
style: compressed

gems:
  - jekyll-angular